apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # This should work with Docker Compose networking
    isDefault: true
    version: 1
    editable: true
    jsonData:
      timeInterval: "15s"