{
 "title": "Receipt Processor",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "/receipts/process Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=~\"/receipts/process\"}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "/metrics Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=~\"/metrics\"}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "/receipts/{{UUID}}/points Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (handler)(rate(http_requests_total{handler=~\"/receipts/[^/]+/points\"}[5m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "/receipts/process Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/receipts/process\"}[5m]) / rate(http_request_duration_seconds_count{handler=\"/receipts/process\"}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "/metrics Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{handler=\"/metrics\"}[5m]) / rate(http_request_duration_seconds_count{handler=\"/metrics\"}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}